Refactored the first blog on kubeslice Office hours
kubeslice/docs pull request #49
Opened 2022-09-05 16:52 UTC by 26tanishabanik

Changed the published date
Changed the description and slug in the doc
Signed off by: Divya Mohan [26tanishabanik@gmail.com](mailto:26tanishabanik@gmail.com)

2022-09-06 04:01 UTC, divya-mohan0209 commented
@26tanishabanik please could you sign the DCO?

2022-09-06 04:04 UTC, divya-mohan0209 requested changes
Nits

2022-09-06 04:04 UTC, divya-mohan0209 commented on blog/2022-09-5-office-hours.mdx
> +description: This is the first post of KubeSlice Office Hours.
```suggestion
description: KubeSlice Office Hours, 25th August 2022.
```

2022-09-06 04:04 UTC, divya-mohan0209 commented on blog/2022-09-5-office-hours.mdx
> +slug: KubeSlice Office Hours, 25th August 2022
```suggestion
slug: 2022-08-25-kubeslice-office-hours
```

2022-09-07 15:23 UTC, amolmote commented
I think @26tanishabanik  you did signoff after opening the PR manually  if i am not wrong. 
Do one think for I have read the DCO action doc, for DCO it is mandatory to signoff while commiting changes to remote repo.
Still you can signoff while squashing all this 6 commits into one (usually it is called as rebase) getting my point??, if not then feel free to ask me on slack i will help you to do this.

2022-09-13 13:22 UTC, closed without merging